export {
  Login,
  Home,
  Register,
  Code,
  Recovery,
  Resend,
} from "./shared/index.shared.js";
export {
  Favorites,
  Profile,
  Buy,
  Services,
  Appointment,
  History,
  BuyProductDetail,
  BuyServiceDetail,
  Address,
  ChangePassword,
  Checkout,
  Edit,
} from "./client/index.client.js";

export {
  AdminHome,
  Users,
  Reports,
  Settings,
  Products,
  ServicesDashboard,
  Categories,
  Sales,
  Comments,
  InfoUser,
  Map,
  InfoSale,
  ClientReport,
  SaleReport,
  ServiceReport,
  ProductReport,
  StockVsSales,
  TopSellingProducts,
  LowRotationProducts,
  ProductRevenue,
  TopRatedProducts,
  MostFavoritedProducts,
  MostViewedProducts,
  SalesByPaymentMethod,
  SalesOvertime,
  SalesRejected,
  RevenueOvertime,
  TopClientBySales,
  NewClientOvertime,
  TopSellingServices,
  ServiceRevenue,
  LowRotationServices,
  Offers,
  BankAccounts,
  EditBankAccount,
  EditProduct,
  EditCategory,
  EditService,
  EditSale,
  EditOffer,
  Schedule,
  Appointments,
  InfoAccount,
  InfoCompany,
} from "./admin/index.admin.js";
