export { default as AdminHome } from "./home/AdminHome";
export { default as Users } from "./users/Users";
export { default as Reports } from "./reports/Reports";
export { default as Settings } from "./settings/Settings";
export { default as Products } from "./products/Products";
export { default as ServicesDashboard } from "./services/Services";
export { default as Categories } from "./categories/Categories";
export { default as Sales } from "./sales/Sales";
export { default as Comments } from "./comments/Comments";
